### ISSUE TITLE
downloading spark-file in /deploy_snowflake.sh fails

### ISSUE THREAD

**Issue by sfc-gh-rfehrmann** [zoharsan/stv2_beta#1]
I think there is a problem with constructing the correct name for spark-file. Tooling like spark-shell is looking for spark-snowflake_2.11-2.8.3.jar and thats the file that has been downloaded. however, the correct filename is 
spark-snowflake_2.11-2.8.3-spark_2.4.jar. Root cause might be that spark_version isn't set in /snowflake_deploy.sh (unless it's set somewhere else) 

<img width="850" alt="Screen Shot 2021-02-05 at 4 46 50 PM" src="https://user-images.githubusercontent.com/60225643/107093695-accfec00-67d3-11eb-8d90-212ce21e0666.png">

**Comment by zoharsan** [comment]
@sfc-gh-rfehrmann You are correct. Variable is not set properly for default Spark driver. It's fixed in the current Dockerfile
