### ISSUE TITLE
Scala Notebooks cannot find spark or snowflake for spark classes

### ISSUE THREAD

**Issue by orellabac** [zoharsan/stv2_beta#3]
Hi.

I was trying out this image (which  I think is a great image)

I wanted to use it to do some spark tests, but if I try an small sample like:
```scala
import org.apache.spark.sql._

//
// Configure your Snowflake environment
//
var sfOptions = Map(
    "sfURL" -> "xxxx.snowflakecomputing.com",
    "sfUser" -> "xxxx",
    "sfPassword" -> "xxx",
    "sfDatabase" -> "xx",
    "sfSchema" -> "xx",
    "sfWarehouse" -> "xx",
    "sfRole" -> "xx"
    )

//
// Create a DataFrame from a Snowflake table
//
val df: DataFrame = sqlContext.read
    .format(SNOWFLAKE_SOURCE_NAME)
    .options(sfOptions)
    .option("dbtable", "information_schema.tables")
    .load()

//
// DataFrames can also be populated via a SQL query
//
val df2: DataFrame = sqlContext.read
    .format(SNOWFLAKE_SOURCE_NAME)
    .options(sfOptions)
    .option("query", "select c1, count(*) from t1 group by c1")
    .load()
```

cmd2.sc:1: object apache is not a member of package org
import org.apache.spark.sql._
           ^cmd2.sc:21: not found: type DataFrame
val df: DataFrame = sqlContext.read
        ^cmd2.sc:30: not found: type DataFrame
val df2: DataFrame = sqlContext.read
         ^cmd2.sc:21: not found: value sqlContext
val df: DataFrame = sqlContext.read
                    ^cmd2.sc:30: not found: value sqlContext
val df2: DataFrame = sqlContext.read
                     ^Compilation Failed

It seems to me that the snowflake references are loaded however they do now work on Scala

**Comment by zoharsan** [comment]
Hi,

Please use the spylon-kernel kernel for Spark Scala API (Not the Scala kernel). The Scala kernel is for Snowpark Scala API support.

Thanks,

Zohar

**Comment by orellabac** [comment]
Thanks!! I tested this and it worked fine
